# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: moogle
  pool: 5
  timeout: 5000
  username: moogle
  password: 

test:
  adapter: postgresql
  database: moogle
  pool: 5
  timeout: 5000
  username: moogle
  password: 

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
